name: Redeploy

on:
  workflow_dispatch:

jobs:
  deploy_to_raspberry:
    name: Deploy Docker image to the Raspberry

    runs-on: ubuntu-latest
    steps:
      - name: Deploy with SSH
        uses: fifsky/ssh-action@v0.0.5
        with:
          # Command to execute on the remote server.
          command: |
            cd ~/duckie-town 
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin 
            docker pull ghcr.io/jass-2021/jass-duckie-town-webservice:arm64
            docker stop duckie-web
            docker rm duckie-web
            docker run -d --name duckie-web --restart=always -p 8080:8080 -v $PWD/DuckieWeb:/root/Documents/DuckieWeb ghcr.io/jass-2021/jass-duckie-town-webservice:arm64
          # Hostname or IP address of the server.
          host: 131.159.38.52
          # Username for authentication.
          user: ubuntu
          # Port number of the server.
          port: 10010
          # String that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
          key: ${{ secrets.SSH_KEY }}
          
  deploy_to_autolab:
    name: Deploy Docker image to autolab

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Open VPN
        run: sudo apt-get install openvpn
      - name: Connect VPN
        uses: golfzaptw/action-connect-ovpn@master
        id: connect_vpn
        with:
          PING_URL: '127.0.0.1'
          FILE_OVPN: '.github/workflows/jass-spb.ovpn'
        env:
          CA_CRT: ${{ secrets.CA_CRT}}
          USER_CRT: ${{ secrets.USER_CRT }}
          USER_KEY: ${{ secrets.USER_KEY }}
      - name: Check Connect VPN
        run: echo ${{ steps.connect_vpn.outputs.STATUS }}
        
      - name: install avahi-utils
        run:  sudo apt install avahi-utils
          
      - name: Deploy with SSH
        uses: fifsky/ssh-action@v0.0.5
        with:
          # Command to execute on the remote server.
          command: |
            cd ~/duckie-town 
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin 
            docker pull ghcr.io/jass-2021/jass-duckie-town-webservice:amd64
            docker stop duckie-web
            docker rm duckie-web
            docker run -d --name duckie-web --restart=always -p 8080:8080 -v $PWD/DuckieWeb:/root/Documents/DuckieWeb ghcr.io/jass-2021/jass-duckie-town-webservice:amd64
          # Hostname or IP address of the server.
          host: 5.19.248.97
          # Username for authentication.
          user: jass
          # Port number of the server.
          port: 2222
          # String that contains a private key for either key-based or hostbased user authentication (OpenSSH format)
          key: ${{ secrets.JASS_USER_KEY }}
          
